### ISSUE TITLE
Cannot parse tddft orca output in gausssum 3.0.2 using updated cclib. some orca outputs work, while heavier ones doesnt

### ISSUE THREAD

**Issue by angelinamary** [cclib/cclib#1509]

**Comment by shivupa** [comment]
Hi do you have some example outputs which can't be parsed in cclib?

**Comment by angelinamary** [comment]
orcaparser of cclib was unable to parse the following parts of ORCA output:
STATE  1:  E=   0.075698 au      2.060 eV    16613.8 cm**-1 <S**2> =   0.000000
   1050a -> 1052a  :     0.135357 (c=  0.36790848)
   1050a -> 1053a  :     0.293973 (c= -0.54219267)

So changing numbers in orcaparser script worked ..issue is solved.
`# Contains SEC or is blank
                while line.strip():
                    start = line[0:9].strip()
                    start = (int(start[:-1]), lookup[start[-1]])
                    end = line[12:19].strip()
                    end = (int(end[:-1]), lookup[end[-1]])
                    # Coeffients are not printed for RPA, only
                    # TDA/CIS.
                    contrib = line[37:49].strip()`

**Comment by berquist** [comment]
The problem will still exist for anyone else who wants to use cclib.  I'd like to fix this in our repository.  Can you share an output file that triggers this?

**Comment by angelinamary** [comment]
Could I please have your email ID to send the output file.

**Comment by shivupa** [comment]
you can send the file directly to me at shivnupadhyay@gmail.com

However, when a situation like this occurs we usually include the file that breaks the code in the test suite as a regression test. This means that the file will be shared publicly in this repo https://github.com/cclib/cclib-data/

Is that acceptable?

**Comment by angelinamary** [comment]
I'm sorry, but the output file is part of a research work and cannot be
shared publicly.
Sincerely,
Angelina Mary

**Comment by shivupa** [comment]
OK fair enough! If you would still like to send it via email, I can try to set up a similar job that replicates the issue. That way the original file will not be shared publicly.

**Comment by angelinamary** [comment]
Thank you for considering... Please find the attached output file. And
please let me know further about the solved code.
 orca.zip
<https://drive.google.com/file/d/1OehojnrBJyPHDza2bM7lH3iN9V2v37HX/view?usp=drive_web>
Sincerely,
Angelina Mary

**Comment by shivupa** [comment]
Hi I think you replied to the emails from github which posts this file publicly!

**Comment by shivupa** [comment]
I will delete your comment from github

**Comment by angelinamary** [comment]
Yes please. Thanks so much.
